name: PHP-Test

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist

    - name: PHPStan Static Analysis
      uses: php-actions/phpstan@v2
      with:
        command: analyse
        configuration: phpstan.neon
        path: src
        memory_limit: 256M
        php_version: 7.4
